### ISSUE TITLE
Remove react 16.9.0 and react-native ^0.62.3 from devDependencies

### ISSUE THREAD

**Issue by Suppi123** [FortAwesome/react-native-fontawesome#107]
We had an issue with react-native-fontawesome because we upgraded to react 17.0.2 and react-native 0.66.0 and Node v16.11.0. These two versions conflicts with react 16.9.0 and react-native ^0.62.3 in the devDependencies. 

Would it make any difference to remove or update these dependencies? 

Thank you in advance!

**Comment by vincentzierigen** [comment]
Same here

**Comment by robmadole** [comment]
Ok, hold up. How are these conflicting with the devDependencies? I think I'm missing something here. The dev deps shouldn't come into play.
