### ISSUE TITLE
Warning 'FontAwesomeIcon' expected 'number'

### ISSUE THREAD

**Issue by vimcat** [FortAwesome/react-native-fontawesome#12]
I'm setting the width and height on my icon per documentation. I get the Warning 'FontAwesomeIcon' expected 'number'.
```
import { FontAwesomeIcon } from '@fortawesome/react-native-fontawesome'
import { faUserCircle } from '@fortawesome/free-regular-svg-icons'

<View>
            <Text><FontAwesomeIcon icon={ faUserCircle } width='10' height='10' /> TEST</Text>
</View>
```

**Comment by mlwilkerson** [comment]
Thanks for the alert, @vimcat.

What happens if you do `width=10` without surrounding the `10` in quotation marks?

**Comment by robmadole** [comment]
Does it need to be `width={10}` to be a number? It's been awhile since I've done React.

**Comment by mlwilkerson** [comment]
Oh, right. Probably.
