### ISSUE TITLE
WARN ERESOLVE overriding peer dependency

### ISSUE THREAD

**Issue by hipaven** [FortAwesome/react-native-fontawesome#120]
npm i --save @fortawesome/fontawesome-svg-core

npm WARN While resolving: XXXX@0.0.1
npm WARN Found: @fortawesome/fontawesome-svg-core@6.1.1
npm WARN node_modules/@fortawesome/fontawesome-svg-core
npm WARN   @fortawesome/fontawesome-svg-core@"^6.1.1" from the root project
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @fortawesome/fontawesome-svg-core@"^1.2.4" from @fortawesome/react-native-fontawesome@0.2.7
npm WARN node_modules/@fortawesome/react-native-fontawesome
npm WARN   @fortawesome/react-native-fontawesome@"^0.2.7" from the root project

**Comment by mkhsharif** [comment]
Just add the dependency manually ```npm i --save @fortawesome/fontawesome-svg-core@"^1.2.4"``` and then run ```npm i --save @fortawesome/fontawesome-svg-core```` again.

**Comment by robmadole** [comment]
This should be resolved now with 0.3.0. Let me know if you try it and it's still broken.
