### ISSUE TITLE
Icon not found after upgrade to v6

### ISSUE THREAD

**Issue by st-cjimenez** [FortAwesome/react-native-fontawesome#124]
I recently upgraded to v6 following the steps indicated in the Readme file. Most things seem to work fine but I keep getting an error saying: `Error: Icon nor found for icon = null` and icons are not displayed. This only happens for icons that have been renamed from v5 to v6. For example, I was using the icon `ellipsis-v` which is now called `ellipsis-vertical` and it doesn't display anymore. 
If I use the new name, the icon shows but I was under the impression that v6 was backwards compatible with v6 and I don't have the time right now to go through each icon and see if it was renamed.
Indeed it seems to be the case that some backward compatibility was built into v6 because when I look into my node_modules folder, I can see that both ellipsis-v and ellipsis-vertical files exist, and that ellipsis-v is just an alias for ellipsis-vertical however referencing ellipsis-v doesn't work

These were my previous dependencies:
    "@fortawesome/fontawesome-svg-core": "^1.2.30",
    "@fortawesome/pro-light-svg-icons": "^5.9.0",
    "@fortawesome/pro-regular-svg-icons": "^5.9.0",
    "@fortawesome/pro-solid-svg-icons": "^5.9.0",
    "@fortawesome/react-native-fontawesome": "^0.2.5"

And these are the new ones:
    "@fortawesome/fontawesome-svg-core": "^6.1.1",
    "@fortawesome/pro-light-svg-icons": "^6.1.1",
    "@fortawesome/pro-regular-svg-icons": "^6.1.1",
    "@fortawesome/pro-solid-svg-icons": "^6.1.1",
    "@fortawesome/react-native-fontawesome": "^0.2.7"
    
**Things I've tried**
Clear yarn cache
Removed node_modules and reinstalled packages

Clear pod cache
Reinstalled pods

**Expected behavior**
All icons should be displayed even if they were renamed on v6.

**Desktop (please complete the following information):**
 - React Native 0.66.4

**Additional context**
![image](https://user-images.githubusercontent.com/89044601/164083288-ca5821b0-94ec-4005-811e-3ed8a09a4699.png)
![simulator_screenshot_A8437376-84B6-4F41-BC8C-41DBC6EA3323](https://user-images.githubusercontent.com/89044601/164083327-e3fdb3b8-94fe-4b78-8b39-106fafccf17c.png)

**Comment by mikhail-ts-live** [comment]
any updates?

**Comment by mikhail-talkshoplive** [comment]
> @st-cjimenez Can you share the code where you are importing the icons?

problem solved, in my case it was like
<FontAwesomeIcon icon={variable} /> 
and in some cases "variable" was null

**Comment by robmadole** [comment]
We've just released 0.3.0 which should fix this without your workaround @mikhail-talkshoplive . If you have time to check please let me know if it's still broken.
