### ISSUE TITLE
npm i @fortawesome/react-native-fontawesome install error

### ISSUE THREAD

**Issue by atologistArpit** [FortAwesome/react-native-fontawesome#138]
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR! 
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login

**Comment by robmadole** [comment]
Hi @atologistArpit . Looks like you may have configured NPM to install using our Font Awesome Pro private registry (that's my guess.) If you are a Pro subscriber you can send an email to `hello@fontawesome.com` and we'll be happy to help you.

If you are not a Pro subscriber please send us the full output of the error log and the output of running `npm config list`.
