### ISSUE TITLE
Where is faFileJpg and faFilePng?????

### ISSUE THREAD

**Issue by cblaze22** [FortAwesome/react-native-fontawesome#168]
Why arent the following icons available?

Where is faFileJpg and faFilePng?????

**Comment by robmadole** [comment]
@cblaze22 this is an old ticket. But those are Pro icons. Happy to re-open if you have another question.

**Comment by cblaze22** [comment]
Are you going to add Pro? I could of sworn there were already Pro icons in
this set.

Mike

**Comment by robmadole** [comment]
We have both free and pro icons available. This library works with both of them. The Pro NPM package can be installed once you have a paid subscription.

**Comment by cblaze22** [comment]
I do have paid subscription. I guess I’ll check again if those options are
available.

Mike
