### ISSUE TITLE
Apple Rejecting all binaries that include Font Awesome with error ITMS-90853: Invalid font

### ISSUE THREAD

**Issue by RayHughes** [FortAwesome/react-native-fontawesome#174]
**Describe the bug**
This week Apple started rejecting all submitted builds that include Font Awesome as an invalid binary. This is affecting every iOS app that uses Font Awesome.  

```
ITMS-90853: Invalid font - There was an error validating the font named 'FontAwesome6Free-Solid' at 'project.name/FontAwesome6_Solid.ttf'. ‘glyf’ table instructions.
```

**Reproducible test case**
The issue occurs when a binary is submitted for App Store review. 

**Expected behavior**
App is not rejected upon submission to App Store review

**Desktop (please complete the following information):**

N/A

**Additional context**
This is likely related to the iOS 18 Font Menu and changes around it. This worked fine up until Monday when Apple announced the iPhone 16

Related Issue in different project: https://github.com/oblador/react-native-vector-icons/issues/1658

**Packages**
    "@fortawesome/fontawesome-free": "^6.6.0",
    "@fortawesome/fontawesome-pro": "^6.6.0",
    "@fortawesome/fontawesome-svg-core": "^6.6.0",
    "@fortawesome/free-brands-svg-icons": "^6.6.0",
    "@fortawesome/free-solid-svg-icons": "^6.6.0",
    "@fortawesome/pro-duotone-svg-icons": "^6.6.0",
    "@fortawesome/pro-light-svg-icons": "^6.6.0",
    "@fortawesome/pro-regular-svg-icons": "^6.6.0",
    "@fortawesome/pro-solid-svg-icons": "^6.6.0",
    "@fortawesome/react-fontawesome": "^0.2.2",
    "@fortawesome/react-native-fontawesome": "^0.3.2",

**Comment by robmadole** [comment]
@RayHughes can you tell me how you are using this file? The `react-native-fontawesome` repo doesn't utilize it.

**Comment by RayHughes** [comment]
@robmadole we are not using it at all. We are using standard FA usage.

**Comment by robmadole** [comment]
You might try removing `@fortawesome/fontawesome-free` and `@fortawesome/fontawesome-pro`. I'm not sure how that TTF file is even being picked up. Has it been added as an asset to your project?

**Comment by RayHughes** [comment]
We just went through our dependency tree and found another library https://github.com/callstack/react-native-paper using FA. We removed the library and builds seem to be working as desired. 

 The error was so vague with Apple and worked 1+ years so we didn't know where to look. Sorry for the report.

**Comment by robmadole** [comment]
No worries! Glad you got if fixed.
