### ISSUE TITLE
The color prop and style does not change the color of icon 

### ISSUE THREAD

**Issue by StasPysmennyi** [FortAwesome/react-native-fontawesome#18]
@The color prop and style does not change the color of icon

**Comment by mlwilkerson** [comment]
Could you submit a code example that reproduces the problem?

**Comment by StasPysmennyi** [comment]
import {FontAwesomeIcon} from '@fortawesome/react-native-fontawesome'
import {faDog, faChevronLeft, faCoffee} from '@fortawesome/free-solid-svg-icons'
<FontAwesomeIcon icon={ faCoffee } style={{ backgroundColor: 'red', color: 'blue' }} />
and color does not set

**Comment by gloompi** [comment]
Similar problem here! I also have `Warning: Failed prop type: Invalid prop `style` of type `array` supplied to `FontAwesomeIcon`, expected `object`` even when I'm not passing any style to component

**Comment by puremana** [comment]
```javascript
import {FontAwesomeIcon} from '@fortawesome/react-native-fontawesome'
import {faDog, faChevronLeft, faCoffee} from '@fortawesome/free-solid-svg-icons'
<FontAwesomeIcon icon={ faCoffee } style={{ backgroundColor: 'red', color: 'blue' }} />
```
This code correctly sets the color and background color with no warning errors on
    "@fortawesome/fontawesome-svg-core": "^1.2.27",
    "@fortawesome/free-brands-svg-icons": "^5.12.1",
    "@fortawesome/free-solid-svg-icons": "^5.12.1",
    "@fortawesome/react-native-fontawesome": "^0.2.1"

**Comment by robmadole** [comment]
I'll re-open this if we can get a reproduction.
