### ISSUE TITLE
Dependencies warning - React 0.60

### ISSUE THREAD

**Issue by lcustodio** [FortAwesome/react-native-fontawesome#23]
**Describe the bug**
![image](https://user-images.githubusercontent.com/585672/62234441-98cb5300-b3c2-11e9-851d-8bb7b73cad61.png)

**Reproducible test case**
Latest version of `react-native init Mahister` (not expo)

**Expected behavior**
I don't think the warning are necessary and the library should handle the latest version.

**Comment by robmadole** [comment]
This should be fixed now.
