### ISSUE TITLE
Does not support style as array

### ISSUE THREAD

**Issue by emusgrave** [FortAwesome/react-native-fontawesome#28]
When wrapping a FontAwesomeIcon component with a library like Styled-Components, a style array is passed to the underlying component instead of an object. This causes a YellowBox warning and also the passed styles do not take effect.

I've experimented and fixed this by calling StyleSheet.flatten on the style within the FontAwesomeIcon component. 

Is there any objection/limitation to making this modification in the library? If not, I'll be happy to submit a PR.

**Comment by vskavgaci** [comment]
same problem

**Comment by cgibsonmm** [comment]
Would love to be able to use arrays with this which would allow for react-native-tailwind to work.

**Comment by joaohd98** [comment]
+1

**Comment by robmadole** [comment]
I'm going to work with @puremana to try and get his [PR merged](https://github.com/FortAwesome/react-native-fontawesome/pull/46)

**Comment by robmadole** [comment]
0.2.3 released to support arrays (thanks @puremana)
