### ISSUE TITLE
Does not work in react-native 0.61.0-rc.2 (patch included)

### ISSUE THREAD

**Issue by ewnavilae** [FortAwesome/react-native-fontawesome#29]
First of all, apologies for not following the template.
I am leaving this issue here in case someone tries to use this package on the latest version of react-native and gets the same error I did, which I believe will be the case.

The error is as follows:
```
Error while updating property 'focusable' of a view managed by RNSVGSvgView

java.lang.String cannot be cast to java.lang.Boolean
```

To fix it, I have applied the following patch using yarn patch-package:

https://gist.github.com/ewnavilae/041493b3df4c97af7bbfc05e94059aea

Should I submit a pull request? I'm not sure if this causes any conflicts with the current version and I'm not used to contributing to open source.

**Comment by kristoferpelchat** [comment]
I am using 0.61.0-rc.2 to address some Hermes issues and I came upon this exact problem. The fixes in this patch solved the issue! A VERY many thanks @ewnavilae !!!!

I would suggest this get PR'd and pushed though. Great work!

**Comment by metachris** [comment]
Thanks for the workaround @ewnavilae 

FortAwesome team - please fix this :)

**Comment by robmadole** [comment]
This fix needs to happen inside of the `react-native-fontawesome` project, not inside the `fontawesome-svg-core`. We'll have to investigate how this can be fixed.

**Comment by robmadole** [comment]
Is this still an issue?

**Comment by iamdavidmartin** [comment]
@robmadole Yes, this is still an issue. I just applied the patch in order to make my app work on android. Here's what in my package.json:
```
    "@fortawesome/fontawesome-svg-core": "^1.2.26",
    "@fortawesome/free-brands-svg-icons": "^5.12.0",
    "@fortawesome/pro-light-svg-icons": "^5.12.0",
    "@fortawesome/pro-solid-svg-icons": "^5.12.0",
    "@fortawesome/react-native-fontawesome": "^0.2.0",
```

**Comment by iamdavidmartin** [comment]
@robmadole this is still an issue, and I have to apply the patch anytime I mess around with node_modules.

Is there any plan to fix this?

**Comment by robmadole** [comment]
@iamdavidmartin we have plans to fix this just haven't gotten to it. PR's are welcome 😉

**Comment by iamdavidmartin** [comment]
@robmadole omg it'll be my first PR. i'm on it!

**Comment by robmadole** [comment]
Well then, let me give you some places to start looking 😸 

As I mentioned, this fix needs to happen in this project and not the `@fortawesome/fontawesome-svg-core`. The basic thing that needs to happen is a transformation of the `focusable` attribute from a string to a boolean.

I think [this](https://github.com/FortAwesome/react-native-fontawesome/blob/master/src/converter.js#L28) is a good place to start.

**Comment by iamdavidmartin** [comment]
Ok. This fixes the problem on my Android simulators and devices and iOS continues to work. I hope this is what you're looking for. Let me know!

**Comment by robmadole** [comment]
PR is perfect @iamdavidmartin ! Thank you. I'll get this merged and a new version released.

**Comment by robmadole** [comment]
I've released 0.2.1, can y'all check it out to see if it fixes the issue?

**Comment by iamdavidmartin** [comment]
Working for me!

**Comment by ewnavilae** [comment]
Great work everyone!
