### ISSUE TITLE
Can I use this library in React360?

### ISSUE THREAD

**Issue by Nyamkhuub** [FortAwesome/react-native-fontawesome#30]
Hello developers!
I am a beginner to React360. So I don't know how to use it. I want to use some icons for my React360 project. How to use it?

Help me?! Thanks all

**Comment by robmadole** [comment]
Hi @Nyamkhuub . I haven't used React360. Perhaps if you ask a more targeted question we might be able to help you. I'll leave this open for a while. (Sorry for the late response)
