### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by jasperkuperus** [FortAwesome/react-native-fontawesome#31]
Hi guys. Thanks for creating this module, it works like a charm. Are you planning to add TypeScript support?

**Comment by braincore** [comment]
Here's a 5-min version for basic usage:

```
declare module '@fortawesome/react-native-fontawesome' {
  import React from 'react';
  import { StyleProp, ViewStyle } from 'react-native';
  import { IconDefinition } from '@fortawesome/free-solid-svg-icons';

  export class FontAwesomeIcon extends React.Component<{ icon: IconDefinition; style: StyleProp<ViewStyle> }> {}
}
```

Save it in a file with `d.ts` extension, e.g. `fontawesome.d.ts`.

**Comment by robmadole** [comment]
We don't have any work on the board to add Typescript support. PRs are welcome! (none of us use TypeScript here)

**Comment by jbarnabe** [comment]
> We don't have any work on the board to add Typescript support. PRs are welcome! (none of us use TypeScript here)

hi @robmadole, there is two pull requests for typescript basic support (#20 & #25 ), is it possible to merge them ?

**Comment by robmadole** [comment]
@jbarnabe yep got those merged. I'll cut a release soon.

**Comment by jbarnabe** [comment]
@robmadole great, thanks !

**Comment by robmadole** [comment]
`0.2.0` released. Let me know how it goes!

**Comment by likern** [comment]
@robmadole Hello, Rob.

I've checked right now and it looks like there is no `index.d.ts` file in the _latest / 0.2.0_ npm package.
My typescript still can't pick up type definitions.
