### ISSUE TITLE
(Documentation improvement): `pod install` required after npm i --save react-native-svg

### ISSUE THREAD

**Issue by iiAtlas** [FortAwesome/react-native-fontawesome#32]
**Is your feature request related to a problem? Please describe.**
When using a bare react-native-cli project, `pod install` must be run to complete the installation of react-native-svg.  Attempting to use `FontAwesomeIcon` on the iOS simulator before completing `pod install` will fail due to RNSVG.

**Describe the solution you'd like**
Add a note to the end of "Installation" recommending you run `pod install` !

**Comment by carineli** [comment]
lifesaver ^
