### ISSUE TITLE
trouble Installing fontawesome Pro using Yarn

### ISSUE THREAD

**Issue by setareh00** [FortAwesome/react-native-fontawesome#41]
Yarn add @fortawesome/pro-light-svg-icons  gives me this Error: 
error https://registry.yarnpkg.com/@fortawesome%2fpro-light-svg-icons: Not found
    at Request.params.callback [as _callback] (/usr/local/lib/node_modules/yarnpkg/lib/util/request-manager.js:273:18)....

 It works when I use NPM but not Yarn . I set .npmrc file as well with the proper Token

**Comment by robmadole** [comment]
@setareh00 if you are still having issues with this send us an email to hello@fontawesome.com
