### ISSUE TITLE
Size in style ignored

### ISSUE THREAD

**Issue by ekkis** [FortAwesome/react-native-fontawesome#43]
**Description**
Setting the icon size works as a separate prop but is ignored in style

**Reproducible test case**
<FontAwesomeIcon icon={faCog} style={{size: 22}}/>

**Expected behavior**
a bigger than normal cog

**Desktop (please complete the following information):**
not a desktop app.  it's react native, so it's mobile: iOS

**Additional context**
frankly I don't see why I would ever want to pass style information in some way other than through the style mechanism.  styles should be kept in a separate structure, not embedded in each tag

**Comment by puremana** [comment]
`size` isn't a valid style property in CSS. Your argument could be why not allow height and width to be set in CSS which you could do, but they are deprecating height and width. Probably because they want to keep the aspect ratio of each icon.

**Comment by ekkis** [comment]
but this isn't CSS.  this is React's own styling system

**Comment by puremana** [comment]
> but this isn't CSS. this is React's own styling system

It's not a property in React styles either, so it wouldn't make sense for this single package to accept a size prop in styles

**Comment by ekkis** [comment]
I guess I don't understand.  the `style` tag is there for styling.  size is part of style.  so style should support size, just like it supports all other kinds of styling.  I don't know why we want to pass size as a separate prop.  it forces me to mark up each component instance instead of doing the reasonable thing: to create a style structure somewhere with all the necessary properties and then use that to mark up my instance

**Comment by robmadole** [comment]
Sorry @ekkis. It may not be ideal but as @puremana said this is not a supported property for `style`. I don't want to overload the `style` with augmented properties. The fact that it's a separate prop is actually desirable since it does something different. Closing this as wont fix.
