### ISSUE TITLE
Could not find type declaration file for '@fortawesome/react-native-fontawesome'

### ISSUE THREAD

**Issue by SocialBrothersDEV** [FortAwesome/react-native-fontawesome#44]
**Describe the bug**
I am not sure if it's a bug or a misconfiguration on my side, but i installed react-native-fontawesome@0.2.1 pro, from the npm.fortawesome registry. My typescript checker fails because it cannot find a type declaration file, while i can see the file in this repo. Maybe it has something to do with the fact that im using the pro version? If its not a bug, excuse me for asking it here. 

**Reproducible test case**
Add a .npmrc to point @fortawesome to npm.fortawesome.com with a authentication token, install `@fortawesome/react-native-fontawesome` and `typescript`, run `yarn tsc`.

**Expected behavior**
To be an index.d.ts in the module.

**Desktop (please complete the following information):**
MacOS
NPM v.6.9.0
Node v10.16.0

**Additional context**
As i said, my thought was that it had something to do with the free/pro versions.

**Comment by Baybars87** [comment]
any clue here ?

**Comment by SocialBrothersDEV** [comment]
> any clue here ?

Do you have the same issue? If so, please thumb up my issue. I thought it had something to do with my local setup, but if more people experience this problem it might be a bug in the npm repo.

**Comment by robmadole** [comment]
@Baybars87 @SocialBrothersDEV I just release 0.2.2. Can you give this version a try?

**Comment by SocialBrothersDEV** [comment]
> @Baybars87 @SocialBrothersDEV I just release 0.2.2. Can you give this version a try?

It's fixed. Thanks!

**Comment by robmadole** [comment]
Awesome!
