### ISSUE TITLE
Exception Thrown

### ISSUE THREAD

**Issue by engineertdog** [FortAwesome/react-native-fontawesome#48]
**Describe the bug**
Trying to implement Fortawesome with a library, but I am getting an exception when I attempt to use an icon in a component, like `<FontAwesomeIcon icon="check-square" />`. 

The exception:

> Exception thrown while executing UI block: - [_NSCFNumber firstObject]: unrecognized selector sent to instance 0xb56a9dea7703dc50

**Reproducible test case**
```
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faCheckSquare,
  faUserTie,
  faLock
} from "@fortawesome/free-solid-svg-icons";

// Font Awesome Initialization
library.add(
  faCheckSquare,
  faUserTie,
  faLock
);

<FontAwesomeIcon icon="check-square" />
```

**Expected behavior**
The icon should be displayed, without an exception.

**Desktop (please complete the following information):**
 - N/A

**Additional context**
Current Versions
```
"@fortawesome/fontawesome-svg-core": "^1.2.27",
"@fortawesome/free-brands-svg-icons": "^5.12.1",
"@fortawesome/free-solid-svg-icons": "^5.12.1",
"@fortawesome/react-native-fontawesome": "^0.2.2",
"react-native-svg": "^11.0.1"
```

**Comment by zelti** [comment]
> Exception thrown while executing UI block: - [_NSCFNumber firstObject]: unrecognized selector sent to instance 0xb56a9dea7703dc50

If you are using expo install the dependencies with expo.. thats solve the problem for me
`expo install react-native-svg`

**Comment by BeckyWu220** [comment]
Switched to react-native-svg version`9.13.3` resolved the issue.

**Comment by arvinio** [comment]
@BeckyWu220 thanks I must've spent half the day trying to solve this
