### ISSUE TITLE
Rewrite documentation for size improvement

### ISSUE THREAD

**Issue by chr4ss1** [FortAwesome/react-native-fontawesome#49]
The problem is if someone follows the advice given in README.MD there is good chance that they will double or triple their codebase size.

For example, after some investigation I found out that more than half of my codebase size was coming from the icons I was using.

I eventually got the size again under the control by seeing the "I don't think three shaking is working' section.

In react-native there is no tree-shaking, so if you don't want to get 4MB+ worth of icons in your app (because you used 7 icons),  you need to import them explicitly:

```
import { faBadgeCheck } from '@fortawesome/pro-solid-svg-icons/faBadgeCheck';
import { faCheck } from '@fortawesome/pro-regular-svg-icons/faCheck';
```

I would propose that no area of the documentation (README.md) should refer to importing icons directly from index.js (or with a big warning), but instead actually import each icon from its concrete icon file, and even better if it would be impossible.

**Comment by robmadole** [comment]
Thanks @ChrisEelmaa! I see. Well that's surprising but it makes sense.

PRs are welcome on this from anyone who is willing. Otherwise I'll add it to the teams todo list and we'll get to it when we can.

**Comment by LouisIV** [comment]
I wrote a babel plugin that fixes this. So that this:

```js
import { faBadgeCheck } from '@fortawesome/pro-solid-svg-icons';
import { faCheck, faCalendar as proCalendarIcon } from '@fortawesome/pro-regular-svg-icons';
```

becomes this:

```js
import { faBadgeCheck } from '@fortawesome/pro-solid-svg-icons/faBadgeCheck';
import { faCheck } from '@fortawesome/pro-regular-svg-icons/faCheck';
import { faCalendar as proCalendarIcon } from '@fortawesome/pro-regular-svg-icons/faCalendar';
```

[Package](https://www.npmjs.com/package/@louislombardo/babel-plugin-fix-font-awesome) | [Repo](https://github.com/LouisIV/fix-font-awesome)
