### ISSUE TITLE
Cannot style color with prop

### ISSUE THREAD

**Issue by jemueller** [FortAwesome/react-native-fontawesome#5]
I'm really glad you guys released this... currently porting a react app over to react native and need this functionality... great job, thanks!

I need to style the icons with a color like you can in the regular @fortawesome/react-fontawesome package... in that package you can just pass a prop like:

`color="red"`

and it will correctly color the icon. This does not appear to be working in this package. Is this feature going to be added? And also is there a way to style the color/size/etc of the icon until this feature is added?

Any help is greatly appreciated. Thanks!

**Comment by jemueller** [comment]
For anyone also curious, browsing through the source I figured out I could set the size by passing the height prop such as

`height="20"`

but I think there is still no ability to set color.

**Comment by mlwilkerson** [comment]
Hey @jemueller , you get the gold medal for opening the first issue!

🥇 

So, yeah, this is bleeding edge at this point. There are several standard features of our `@fortawesome/react-fontawesome` that we're in the process of porting over, including style. Some of them, in `react-fontawesome` are normally accomplished using CSS, so we'll have to implement them instead in whatever way appropriate for React Native.

PRs welcome :wink:

**Comment by mlwilkerson** [comment]
Just merged #8 that provides support for setting color. Will release to npm soon.
