### ISSUE TITLE
prop types exports are deprecated in react native

### ISSUE THREAD

**Issue by pcmaffey** [FortAwesome/react-native-fontawesome#50]
They've also been removed in react-native-web. Thus, this library is throwing exception:

` _reactNative.ViewPropTypes is undefined`

**Comment by robmadole** [comment]
@pcmaffey is it replaced by something else?

**Comment by pcmaffey** [comment]
They switched to flow types. https://github.com/facebook/react-native/blob/07fd3125c8c103209143cbc90759da40fceb5c1e/Libraries/Components/View/ViewPropTypes.js

**Comment by robmadole** [comment]
I'm not seeing an exception in our latest release 0.3.0. If someone runs into this let me know how to reproduce.
