### ISSUE TITLE
Warning of peer dependency

### ISSUE THREAD

**Issue by ekkis** [FortAwesome/react-native-fontawesome#52]
whenever I install any package in my project I get the warning:

> npm WARN @fortawesome/react-native-fontawesome@0.2.2 requires a peer of react-native@^0.57 but none is installed. You must install peer dependencies yourself.

but I have react native installed:
```
# grep react-native package.json
```
yields:

> "react-native": "~0.61.4",

so what is the problem here?

p.s.

I also get:

> npm WARN @fortawesome/react-native-fontawesome@0.2.2 requires a peer of react-native-svg@^7.0 || ^8.0 || ^9.0 but none is installed. You must install peer dependencies yourself.

though I have 11.0.1 installed

**Comment by robmadole** [comment]
@ekkis yeah these projects change very quickly so our deps are just out-of-date.

I will work to get these updated.

**Comment by ekkis** [comment]
thanks mate.  it's hard to keep up with the rate of change

**Comment by robmadole** [comment]
@ekkis just release 0.2.4. Can you give that a try?
