### ISSUE TITLE
Icons from free-brands-svg-icons not found

### ISSUE THREAD

**Issue by dejawho** [FortAwesome/react-native-fontawesome#57]
Hi, 
I'm using FontAwsome on react native, I followed the installation instructions and I have created my library inside the App.js file. The library is defined like this:

```
import { library } from '@fortawesome/fontawesome-svg-core';
import { faRebel } from '@fortawesome/free-brands-svg-icons';
import { faCalendarPlus, faMapMarkerAlt, faHandshake, faFutbol } from '@fortawesome/free-solid-svg-icons';

library.add(faCalendarPlus, faMapMarkerAlt, faHandshake, faFutbol, faRebel);
```

Now I load the icon by name with 

`  <FontAwesomeIcon icon={this.props.icon} size={componentHeight} style={{marginRight: 2}} color={this.props.iconColor} />`

Where this.props.icon is the name, it works correctly for calendar-plus, map-marker-alt and the others from free-solid-svg-icons. But if i try to load the rebel icon it say icon not found rebel.

The strange thing is that if I do something like: 
```
import { faRebel } from '@fortawesome/free-brands-svg-icons';
<FontAwesomeIcon icon={faRebel} size={componentHeight} style={{marginRight: 2}} color={this.props.iconColor} />

```
This seems to work, so the icont actually exist, but it can't be found in the library. Is this a bug?

**Comment by robmadole** [comment]
@dejawho try setting `this.props.icon` = `['fab', 'rebel']`

Since it's not in the "solid" style you need to make sure and give the prefix.

**Comment by dejawho** [comment]
> @dejawho try setting `this.props.icon` = `['fab', 'rebel']`
> 
> Since it's not in the "solid" style you need to make sure and give the prefix.

thanks, it worked
