### ISSUE TITLE
Rotation can cause cropping

### ISSUE THREAD

**Issue by aiba** [FortAwesome/react-native-fontawesome#64]
Rotating an icon seems to crop the edges, and this not desirable.

```js
import { faSyncAlt } from '@fortawesome/pro-solid-svg-icons'
<FontAwesomeIcon icon=faSyncAlt transform={{ rotate: 45 }} />
```

<img width="129" alt="image" src="https://user-images.githubusercontent.com/26651/83064103-403f0380-a02f-11ea-9485-42f60edc638a.png">

**Comment by robmadole** [comment]
@aiba if you can provide a complete reproduction we'd be happy to take a look. You can use something like codepen.io or codesandbox.io. I'll re-open the issue as soon as you provide the reproduction.

**Comment by aiba** [comment]
I thought the code I pasted was pretty clear, and this only applies to the react-native fontawesome library, so I can't create a codepen reproduction.  (You'd have to run in a device simulator).

But in any case, I discovered a workaround: just wrap the FontAwesomeIcon in a react-native View comonent, and apply the rotation transform to the outer View.  Doing this will not crop the icon.
