### ISSUE TITLE
Not working on newer version of React Native for Web (ViewPropTypes are removed)

### ISSUE THREAD

**Issue by aikewoody** [FortAwesome/react-native-fontawesome#72]
**Describe the bug**
With the newest version of `react-native-web` (^0.13.13) and the latest version of `@fortawesome/react-native-fontawesome` (^0.2.5) the project crashes:
```
TypeError: Cannot read property 'style' of undefined
../../../@fortawesome/react-native-fontawesome/dist/components/FontAwesomeIcon.js
node_modules/@fortawesome/react-native-fontawesome/dist/components/FontAwesomeIcon.js:149
  146 | color: _propTypes["default"].string,
  147 | secondaryColor: _propTypes["default"].string,
  148 | secondaryOpacity: _propTypes["default"].number,
> 149 | style: _propTypes["default"].oneOfType([_propTypes["default"].shape(_objectSpread({}, _reactNative.ViewPropTypes.style)), _propTypes["default"].array]),
```

**Reproducible test case**
Install the following packages and run the project (`npm run start:web`):

- "react-native-web": "^0.13.13",
- "@fortawesome/react-native-fontawesome": "^0.2.5",

**Expected behavior**
It is expected that the project is able to be build and run without errors.

**Additional context**
This problem is caused by the deletion of the `ViewPropTypes` export from the `react-native-web` package.

The maintainer of `react-native-web` said the following about this:
"React Native is going to stop exporting prop types so libraries should stop depending on them. I don't plan to add them back to RNfW"
[https://github.com/necolas/react-native-web/issues/1543](https://github.com/necolas/react-native-web/issues/1543)

**Comment by golya** [comment]
https://github.com/FortAwesome/react-native-fontawesome/pull/73
I added this pull request to resolve this issue.

**Comment by rvdende** [comment]
@golya thanks for this! Saved me a lot of headache. PR should get merged.

**Comment by robmadole** [comment]
0.2.6 is released from @golya PR. Thanks again.
