### ISSUE TITLE
RNSVGPath was not found in the UIManager

### ISSUE THREAD

**Issue by kaseychakos** [FortAwesome/react-native-fontawesome#81]
I followed the instructions and even the basic explicit import example did not work for my functional component. Any suggestions? I've tried all sorts of imports and re-installing packages even react-native-svg which I wasn't really wanting to do since the documentation advises against it. Thanks for the help in advance.

`import { FontAwesomeIcon } from '@fortawesome/react-native-fontawesome'
  import { faCoffee } from '@fortawesome/free-solid-svg-icons'
...
 <FontAwesomeIcon icon={faCoffee} />
`
Console Output:

[Error] Invariant Violation: requireNativeComponent: "RNSVGPath" was not found in the UIManager.

This error is located at:
    in RNSVGPath (at Path.tsx:14)
    in Path (created by FontAwesomeIcon)
    in RNSVGGroup (at G.tsx:33)
    in G (at Svg.tsx:202)
    in RNSVGSvgView (at Svg.tsx:197)
    in Svg (created by FontAwesomeIcon)
    in FontAwesomeIcon (at Mail.js:50)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at GenericTouchable.js:270)
    in RNGestureHandlerButton (at createNativeWrapper.js:47)
    in NativeViewGestureHandler (at createNativeWrapper.js:46)
    in ComponentWrapper (at GestureButtons.js:66)
    in BaseButton (at GenericTouchable.js:259)
    in GenericTouchable (at TouchableOpacity.js:52)
    in TouchableOpacity (at Mail.js:49)
    in RCTView (at View.js:34)
    in View (at Mail.js:48)
    in RCTView (at View.js:34)
    in View (at Mail.js:45)
    in RCTView (at View.js:34)
    in View (at Mail.js:44)
    in Login (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:245)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:244)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:573)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in RCTView (at View.js:34)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:619)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:84)
    in MaybeScreen (at CardStack.tsx:612)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:54)
    in MaybeScreenContainer (at CardStack.tsx:494)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:74)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in RCTView (at View.js:34)
    in View (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at App.js:51)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:409)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at App.js:50)
    in ThemeProvider (at Provider.tsx:83)
    in RCTView (at View.js:34)
    in View (at PortalHost.tsx:126)
    in Portal.Host (at Provider.tsx:81)
    in Provider (at App.js:49)
    in App (at Project/index.js:23)
    in ThemeProvider (at Provider.tsx:83)
    in RCTView (at View.js:34)
    in View (at PortalHost.tsx:126)
    in Portal.Host (at Provider.tsx:81)
    in Provider (at Project/index.js:22)
    in Main (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
	error
	reactConsoleErrorHandler (index.bundle:27745)
	n (index.bundle:42003)
	registerError (index.bundle:72098)
	errorImpl (index.bundle:72005)
	(anonymous function) (index.bundle:71982)
	reportException (index.bundle:27690)
	handleException (index.bundle:27738)
	showErrorDialog (index.bundle:46345)
	logCapturedError (index.bundle:23123)
	logError (index.bundle:23195)
	(anonymous function) (index.bundle:24164)
	callCallback (index.bundle:17532)
	commitUpdateQueue (index.bundle:17554)
	commitLifeCycles (index.bundle:23486)
	commitLayoutEffects (index.bundle:25682)
	invokeGuardedCallbackImpl (index.bundle:12903)
	invokeGuardedCallback (index.bundle:12997)
	commitRootImpl (index.bundle:25471)
	commitRootImpl
	unstable_runWithPriority (index.bundle:47312)
	commitRoot (index.bundle:25358)
	performSyncWorkOnRoot (index.bundle:24882)
	performSyncWorkOnRoot
	(anonymous function) (index.bundle:16154)
	unstable_runWithPriority (index.bundle:47312)
	flushSyncCallbackQueueImpl (index.bundle:16149)
	flushSyncCallbackQueue (index.bundle:16138)
	scheduleUpdateOnFiber (index.bundle:24491)
	dispatchAction (index.bundle:20192)
	dispatchAction
	(anonymous function) (index.bundle:148917)
	(anonymous function) (index.bundle:150110)
	dispatch (index.bundle:149997)
	dispatch (index.bundle:149863)
	(anonymous function) (index.bundle:149870)
	(anonymous function) (index.bundle:106878)
	tryCallOne (index.bundle:5597)
	(anonymous function) (index.bundle:5698)
	_callTimer (index.bundle:30716)
	_callImmediatesPass (index.bundle:30755)
	callImmediates (index.bundle:30972)
	__callImmediates (index.bundle:4891)
	(anonymous function) (index.bundle:4677)
	__guard (index.bundle:4874)
	flushedQueue (index.bundle:4676)
	flushedQueue
	callFunctionReturnFlushedQueue
	(anonymous function) (debuggerWorker.aca173c4.js:4:908)

**Comment by kaseychakos** [comment]
FontAwesome works with:
`import Icon from 'react-native-vector-icons/FontAwesome';`
...
`         <Icon
              name='user-circle'
              size={24}
              color='grey'
            />
`
Trying to use the alternate icons is what led me down this path. MUI and others just name the icons different so you don't run into issues like this.. hope this additional information helps to debug.. ICONS haha. To be fair I really do like the look of FontAwesome and I'm fairly new to React Native so it's probably something I am doing wrong but still kind of funny. Could 'react-native-vector-icons/FontAwesome' be conflicting in some way?

**Comment by FlorianGG** [comment]
> FontAwesome works with: `import Icon from 'react-native-vector-icons/FontAwesome';` ... ` <Icon name='user-circle' size={24} color='grey' />` Trying to use the alternate icons is what led me down this path.

He does not use `react-native-vector-icons/FontAwesome` but `@fortawesome/react-native-fontawesome`. And I have the same problem

**Comment by robmadole** [comment]
Make sure you've explicitly installed `react-native-svg` in your `package.json` and ran `pod install` in the `ios` directory. I know this is an old issue so going to close but I can reopen if there are still issues.
