### ISSUE TITLE
Support most recent react version

### ISSUE THREAD

**Issue by nmokkenstorm** [FortAwesome/react-native-fontawesome#85]
**Is your feature request related to a problem? Please describe.**
React Native / Expo both work on the most recent version of React, but this library does not.

**Describe the solution you'd like**
I'd like this library to support React 17. Seeing as the release itself didn't add any features, I think it should be a smooth upgrade by just changing package.json. The more sustainable solution would be to mark React as a peer dependency

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by RayHughes** [comment]
https://github.com/FortAwesome/react-native-fontawesome/pull/86 -- looks like someone got it.

**Comment by matkastner** [comment]
Added a PR for this #98

**Comment by matkastner** [comment]
@nmokkenstorm @RayHughes v0.2.7 has been released by @robmadole to fix this :D

**Comment by nmokkenstorm** [comment]
> @nmokkenstorm @RayHughes v0.2.7 has been released by @robmadole to fix this :D

Thanks, I'll close the issue!
